-- Scene pipeline job types (GENERATE_SCENE / REVIEW_FOOTAGE / MATCH_SCENES)
ALTER TYPE "JobType" ADD VALUE 'GENERATE_SCENE';
ALTER TYPE "JobType" ADD VALUE 'REVIEW_FOOTAGE';
ALTER TYPE "JobType" ADD VALUE 'MATCH_SCENES';
